### ISSUE TITLE
Create false positive / false negative line graphs for each scatterplot point

### ISSUE THREAD

**Issue by elovero** [flatironinstitute/spikeforest-docs#54] opened 2019-01-11 17:05 UTC
![image](https://user-images.githubusercontent.com/44589448/51048520-2b2c1680-1599-11e9-8082-61af3b5d5d88.png)

**Comment by magland** [comment] 2019-01-17 19:33
Duplicate of #53

**Closed by magland** 2019-01-17 19:33 UTC
